services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379



  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
