services:
  bot:
    build: .
    container_name: bot_support
    restart: unless-stopped
    env_file:
      - data/.env
    volumes:
      - sqlite_data:/data
    networks:
      - app_network


  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  sqlite_data:

networks:
  app_network:
    driver: bridge
